blog/urls.py
from django.urls import path, include
from django.contrib import admin
from django.contrib.auth import views


urlpatterns = [
    path('', include('blog.urlsView')),
]

livraria/urls.py
from django.urls import path, include
from django.conf.urls import url

from django.contrib.auth import views
from django.contrib import admin


from django.views.generic.base import TemplateView
from .views import SignUpView, IndexView ,CreateLivroView, CreateEditoraView, CreateAutorView,CreateEmprestimoLivro, ListEmprestimosView, UpdateEmprestimoView, LivrosListView,LivrosDetailView, UpdateLivroView, DeleteLivroView, ProfileUserView, UpdateUserView

from django.contrib.auth import views as auth_views

app_name = 'livraria'

urlpatterns = [
    path('', IndexView.as_view(), name='home'),

    url(r'^atualizarconta/(?P<pk>[0-9]+)/$', UpdateUserView.as_view(), name='updateuser'),
    path('minhaconta', ProfileUserView.as_view(), name='profileuser'),
    #Cadastros
    path('registrousuario', SignUpView.as_view(), name='registeruser'),
    path('cadastrolivro', CreateLivroView.as_view(),name='cadastrarlivro'),
    path('cadastroeditora', CreateEditoraView.as_view(), name='cadastrareditora'),
    path('cadastroautor', CreateAutorView.as_view(), name='cadastrarautor'),

    #Emprestimo
    path('<int:pk>/emprestimolivro/', CreateEmprestimoLivro.as_view(), name='emprestarlivro'),

    path('exibiremprestimos', ListEmprestimosView.as_view(), name='listaremprestimos'),


     url(r'^devolucaolivro/(?P<pk>[0-9]+)/$', UpdateEmprestimoView.as_view(), name='devolverlivro'),

    #Exibição de livros
    path('exibirlivros', LivrosListView.as_view(), name='listarlivros'),

    #detalhe
    url(r'^detalhelivro/(?P<pk>[0-9]+)/$', LivrosDetailView.as_view(), name='detaillivro'),

    #Editar

    url(r'^edicaolivro/(?P<pk>[0-9]+)/$', UpdateLivroView.as_view(), name='editarlivro'),

    #excluir livro
    path('<int:pk>deletarlivro', DeleteLivroView.as_view(), name='deletelivro'),

    #Devolver Livro
    ##path('/livraria_devolver_livro/<int:pk>',livraria_devolver_livro, name='livrariadevolverlivro')

]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views
from django.contrib.auth import views as auth_views

urlpatterns = [
  
    path('admin/', admin.site.urls),
    path('accounts/',include('django.contrib.auth.urls')),
   # path('accounts/login/', views.LoginView.as_view(), name='login'),
   # path('accounts/logout/', views.LogoutView.as_view(next_page='/'), name='logout'),
    #path('accounts/password_change/', views.PasswordChangeForm.as_view(), name='change'),
 
    path('blog', include('blog.urls'), name='blog'),  
    path('', include('livraria.urls')),
 
]

blog/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.db.models import Sum


class Post(models.Model): # Utilizando Herança com Python Post é um Model
    # Definindo a chave estrangeira 
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()


    create_date = models.DateField(auto_now=True)

    #definindo data e hora e o campo pode ser nulo
    published_date = models.DateField(blank=True, null=True)
    views = models.BigIntegerField(default=0)
    

    def publish(self):
        #Pega a data e hora atual e altera a data de publicação para realizar o salvamento de dados no banco de dados
        self.published_date = timezone.now()
        self.save()

    def __str__(self): #Retorna a string do objeto em memória
        return '{} ({})'.format(self.title, self.author)

    def approved_comments(self):
        return self.comments.filter(approved_comment=True)


    def likes_count(self):

        count = self.opinion.aggregate(Sum('like'))

        if count['like__sum'] == None :
            count['like__sum'] = 0
    
        return count['like__sum'] #retorna a quantidade de PostLike no Post, como sendo filtro a proprio objeto Post

    def deslikes_count(self):
        count = self.opinion.aggregate(Sum('deslike'))

        if count['deslike__sum'] == None :
            count['deslike__sum'] = 0

        return count['deslike__sum']

class Opinion(models.Model):
    like = models.IntegerField(default=0)
    deslike = models.IntegerField(default=0)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    post = models.ForeignKey('blog.Post', on_delete=models.CASCADE, related_name='opinion')
    create_date = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return "'{}' '{}' '{}' '{}'".format(self.post.title, self.user,self.like,self.deslike)

class PostLike(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    post = models.ForeignKey('blog.Post', on_delete=models.CASCADE)
    create_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "'{}' - '{}'".format(self.post.title, self.user)

class Comment(models.Model):
    post = models.ForeignKey('blog.Post', on_delete=models.CASCADE, related_name='comments')
    author = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save()

    def __str__(self):
        return self.text

livraria/views.py
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin


from django.views.generic.edit import CreateView
from django.views.generic import TemplateView, ListView, DetailView, DeleteView, UpdateView

from django.urls import reverse_lazy

from .forms import CustomUsuarioCreationForm, CustomUsuarioChangeForm ,LivroCreationForm, EditoraCreateForm, AutorCreationForm, EmprestimoLivroCreationForm

from .models import Livro, Categoria, Autor, Editora, Endereco, EmprestimoLivro, CustomUsuario

from django.shortcuts import render, reverse, redirect, get_object_or_404
from django.contrib import messages
from django.utils import timezone

from django.contrib.auth.forms import PasswordChangeForm



# ----------- Variáveis globais ------------

verificacao_campo_data_devolucao = None
verificacao_campo_quantidade = None
aux_instance_form = None
verificacao_botao_salvar = True




# ----------- DeleteView ------------

class DeleteLivroView(DeleteView):
    model = Livro
    template_name = 'livraria/forms/livro_confirm_delet.html'
    success_url = reverse_lazy('livraria:listarlivros')
    success_message = 'Livro deletado com sucesso!'


# ----------- DetailView ------------

class LivrosDetailView(DetailView):
     model = Livro
    #queryset = Livro.objects.all()
     template_name = 'livraria/produto/detalhe_livro.html'

    #def get(self, request, *args, **kwargs):
     #   livro = get_object_or_404(Livro, pk=kwargs['pk'])
      #  context = {'livro': livro}
      #  return render(request, 'livraria/produto/detalhe_livro.html', context)
   # def get_object(self):
     #  id_ = self.kwargs.get("id")
      #  return get_object_or_404(Livro, id=id_)

# ----------- ListView ------------

class LivrosListView(ListView):
    model = Livro
    template_name = 'livraria/produto/exibir_livros.html'
    queryset = Livro.objects.all()
    context_object_name = 'livros'


class ListEmprestimosView(ListView):
    model = EmprestimoLivro
    template_name = 'livraria/produto/exibir_emprestimos.html'
    queryset = EmprestimoLivro.objects.all()
    context_object_name = 'emprestimos'


class IndexView(ListView):
    models = Livro
    template_name = 'livraria/home.html'
    queryset = Livro.objects.all()
    context_object_name = 'livros'


# ----------- CreateView ------------

class SignUpView(SuccessMessageMixin,CreateView):
    form_class = CustomUsuarioCreationForm
    success_url = reverse_lazy('livraria:registeruser')
    template_name = 'livraria/register_user.html'
    success_message = 'Cadastro efetuado com sucesso!'


class CreateLivroView(LoginRequiredMixin, SuccessMessageMixin,CreateView):
    login_url = 'login'
    redirect_field_name = 'login'
    form_class = LivroCreationForm
    success_url = reverse_lazy('livraria:cadastrarlivro')
    template_name = 'livraria/forms/add_livro.html'

    def get(self, request, *args, **kwargs):
        autores = Autor.objects.all()
        editoras = Editora.objects.all()
        formLivro = super(CreateLivroView, self).get_form()
        context = {'formLivro': formLivro,
                   'autores': autores,
                   'editoras': editoras}
        return render(request, 'livraria/forms/add_livro.html',context)

    def post(self, request, *args, **kwargs):
        formLivro = self.get_form()
        autores = Autor.objects.all()
        editoras = Editora.objects.all()


        if formLivro.is_valid():
            nome = formLivro.cleaned_data['nome']
            preco = formLivro.cleaned_data['preco']
            estoque = formLivro.cleaned_data['estoque'] 
            edicao = formLivro.cleaned_data['edicao']
            ano = formLivro.cleaned_data['ano']
            num_paginas = formLivro.cleaned_data['num_paginas']
            descricao = formLivro.cleaned_data['descricao']

            editora = formLivro.cleaned_data['editora']
            autor = formLivro.cleaned_data['autor'] 
            categoria = formLivro.cleaned_data['categoria']


            print(formLivro.cleaned_data)
            if estoque <= 0:
                messages.error(request,'O estoque não pode ser zero ou negativo')

            elif num_paginas <= 0:
                messages.error(request,'O número de páginas não pode ser zero ou negativo')

            else:

                aux_editora, created = Editora.objects.get_or_create(id=editora.id)
                aux_autor, created = Autor.objects.get_or_create(id=autor.id)
                aux_categoria, created = Categoria.objects.get_or_create(nome=categoria)
            
                preco_total = preco * estoque
                
                livro, created = Livro.objects.get_or_create(nome=nome, preco=preco, estoque=estoque, edicao=edicao, ano=ano, num_paginas=num_paginas, descricao=descricao, editora=aux_editora, autor=aux_autor, categoria=aux_categoria, preco_total=preco_total)

                messages.success(request,'Cadastro realizado com sucesso!')
                livro.save()
                
                formLivro = LivroCreationForm()


        context = {'formLivro': formLivro,
                   'editoras': editoras,
                   'autores': autores
                  }

        return render(request, 'livraria/forms/add_livro.html' , context)


class CreateEditoraView(LoginRequiredMixin, CreateView):
    login_url = 'login'
    redirect_field_name = 'login'
    model = Editora
    form_class = EditoraCreateForm
    success_url = reverse_lazy('livraria:cadastrareditora')

    def get(self, request, *args, **kwargs):
        form = super(CreateEditoraView, self).get_form()
        context = {'formEditora': form}
        return render(request, 'livraria/forms/add_editora.html', context)

    def post(self, request, *args, **kwargs):
        formEditora = self.get_form()

        if formEditora.is_valid():

            rua = formEditora.cleaned_data['rua']
            bairro = formEditora.cleaned_data['bairro']
            cidade = formEditora.cleaned_data['cidade']
            estado = formEditora.cleaned_data['estado']
            numero = formEditora.cleaned_data['numero']
            nomeEditora = formEditora.cleaned_data['nome']

            endereco, created = Endereco.objects.get_or_create(rua=rua, bairro=bairro, numero=numero, cidade=cidade, estado=estado)
            editora, created = Editora.objects.get_or_create(nome=nomeEditora, endereco=endereco)
            messages.success(request,'Cadastro realizado com sucesso!')
            editora.save()

        formEditora = EditoraCreateForm()

        return render(request, 'livraria/forms/add_editora.html', {'formEditora': formEditora})


class CreateAutorView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    login_url = 'login'
    redirect_field_name = 'login'
    form_class = AutorCreationForm
    template_name = 'livraria/forms/add_autor.html'
    success_url = reverse_lazy('livraria:cadastrarautor')

    def get(self, request, *args, **kwargs):
        formAutor = super(CreateAutorView, self).get_form()
        context = {'formAutor': formAutor}
        return render(request, 'livraria/forms/add_autor.html',context)

    def post(self, request, *args, **kwargs):
        formAutor = self.get_form()

        if formAutor.is_valid():

            nome = formAutor.cleaned_data['nome']
            data_nascimento = formAutor.cleaned_data['data_nascimento']
            print('data nascimento:', data_nascimento)
            autor, created = Autor.objects.get_or_create(nome=nome, data_nascimento=data_nascimento)
            messages.success(request,'Cadastro realizado com sucesso!')
            autor.save()

        formAutor = AutorCreationForm()
        

        return render(request, 'livraria/forms/add_autor.html' , {'formAutor': formAutor})


class CreateEmprestimoLivro(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    login_url = 'login'
    redirect_field_name = 'login'
    form_class = EmprestimoLivroCreationForm
    template_name = 'livraria/forms/emprestimo_livro.html'

    def get(self, request, *args, **kwargs):
        livro = Livro.objects.get(pk=self.kwargs['pk'])
        formEmprestimo = super(CreateEmprestimoLivro, self).get_form()
        global verificacao_botao_salvar
        #aux_instance_form = formEmprestimo


        context = {'formEmprestimo': formEmprestimo,
                   'livro': livro, 
                   'verificacao_botao_salvar':verificacao_botao_salvar
                   }
        
        return render(request, 'livraria/forms/emprestimo_livro.html',context)

    def post(self, request, *args, **kwargs):

        livro = Livro.objects.get(pk=self.kwargs['pk'])
        global verificacao_campo_data_devolucao
        global verificacao_campo_quantidade
        global aux_instance_form
        global verificacao_botao_salvar

        if verificacao_campo_data_devolucao == None and verificacao_campo_quantidade == None: 
            formEmprestimo = self.get_form()
            aux_instance_form = formEmprestimo
           # print('FORM emprestimo:', formEmprestimo)
            print('CAiu na verificação da data')
        else:
            print('CAiu no else')
            formEmprestimo = aux_instance_form
      
        if formEmprestimo.is_valid():
            quantidade = formEmprestimo.cleaned_data['quantidade']
            data_inicial = formEmprestimo.cleaned_data['data_inicial']
            data_devolucao = formEmprestimo.cleaned_data['data_devolucao']
            preco_total = formEmprestimo.cleaned_data['preco']
            diferenca_data = data_devolucao - data_inicial

            print('DATA INCIAL', data_inicial)
            print('DATA DEVOULAÇÂO:', data_devolucao)
            print('DIFERENÇA', diferenca_data.days)
            if quantidade == 0:
                
                messages.error(request,'A quantidade não pode ser zero')

            elif quantidade > livro.estoque:

templates/livraria/base.html
<!DOCTYPE html>
{% load static %}

<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">

    
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

        <!--Estilos da base -->
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">

        <!--Estilos do footer -->
    <link rel="stylesheet" href="{% static 'css/footer.css' %}">
    
    <!--Estilos-->
    <link rel="stylesheet" type="text/css" href="{% static 'css/util_FS_P_M.css' %}">
    
    <link rel="stylesheet" type="text/css" href="{% static 'css/util.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
</head>




<header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
    <div class="container">
      <a class="navbar-brand fs-30" href="/">Livraria</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class = "collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">

          <li class="nav-item active p-t-5">
            <a class="fs-15 text-white p-t-6 linkblog"nav-link href="{% url 'blog:post_list' %}">Conheça nosso blog
            <span class="material-icons p-t-1">article</span>
          </a>
          </li>
          {% if user.is_authenticated %}
             <li class="nav-item dropdown">
                    <a href="#" class="nav-link dropdown-toggle fs-15 text-white" data-toggle="dropdown">Serviços</a>
                    <div class="dropdown-menu">
                      <div class="dropdown-header">Listagem</div>
                      <a href="{% url 'livraria:listarlivros' %}" class="dropdown-item">Livros</a>

                
                      <a href="{% url 'livraria:listaremprestimos' %}" class="dropdown-item">Empréstimos</a>
                     
                      <div class="dropdown-header">Cadastros</div>
                      <a href="{% url 'livraria:cadastrarlivro' %}" class="dropdown-item">Livro</a>

                      <a href="{% url 'livraria:cadastrareditora' %}" class="dropdown-item">Editora</a>

                      <a href="{% url 'livraria:cadastrarautor' %}" class="dropdown-item">Autor</a>
 
                    </div>
                </li>
           
            <li class="nav-item dropdown p-r-30">
              <a href="#" class="nav-link dropdown-toggle fs-15 text-white " data-toggle="dropdown">Seja bem vindo, {{ user.first_name }} {{user.last_name}}</a>
              <div class="dropdown-menu">
                <a href="{% url 'livraria:profileuser' %}" class="dropdown-item">Minha conta</a>
              </div>
          </li>



            <li class="nav-item">
                <a href="{% url 'logout' %}">
                <button type="button"  class="btn btn-primary btn-sm">
                    <span class="material-icons">input</span>
                    Sair
                 </button>
                </a>
            </li>

            {% else %}
             <a href="{% url 'login' %}" class="top-menu"><span class="material-icons p-t-6 ">lock</span></a>
            {% endif %} 
        </ul>
      </div>
    </div>
      </nav>
  </nav>
</header>
<body style="background-image: url({% static 'images/background_login.jpg' %})">
    {% block content %}
    {% endblock %}
</body>
  

<div class="mt-5 pt-4 pb-5 footer bg-dark">
  <div class="container">
    <div class="row">
      <div class="col-lg-5 col-xs-12 about-company">
  
          <div class="card-body">
          <h5 class="card-title text-white display-4 fs-30">Redes Sociais</h5>
          <p class="text-white fs-20">Conheça nossos trabalhos através de nossas redes sociais :D </p>
      
              <a class="text-light" href="https://pt-br.facebook.com/"><i class="fa fa-facebook-square fa-fw fa-2x"></i></a>
            
              <a class="text-light" href="https://twitter.com/login?lang=pt"><i class="fa fa-twitter-square fa-fw fa-2x"></i></a>
            
              <a class="text-light" href="https://www.instagram.com/?hl=pt-br"><i class="fa fa-instagram fa-fw fa-2x"></i></a>
            
              <a class="text-light" href="https://br.linkedin.com/"><i class="fa fa-linkedin fa-fw fa-2x"></i></a>
            
  
        </div>
       </div>	
  
      
      
       <div class="col-lg-3 col-xs-12 links">
          <ul class="m-0 p-0">
          </ul>
      </div>
      <div class="col-lg-4 col-xs-12 location">
        <h4 class="mt-lg-0 mt-sm-4 ">Local</h4>
        <p class="text-white p-t-13 p-b-9 fs-20">00, Lorem ipsum dolor, consectetur adipiscing</p>
        <p class="mb-0 text-white fs-20"><i class="fa fa-phone mr-3"></i>(00) 000-000</p>
        <p class="text-white fs-20"><i class="fa fa-envelope-o mr-3 text-white"></i>info@livraria.com</p>
      </div>
    </div>

    <div class="row mt-6">
      <div class="col copyright">
        <p class="text-white fs-20"><small class="text-white">&copy; {% now 'Y' %}</small></p>
      </div>
    </div>
  </div>
</div>



<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootbox.js/5.4.0/bootbox.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/d3js/5.15.1/d3.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>

<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<!-- 
<script src='https://unpkg.com/sweetalert2@7.12.15/dist/sweetalert2.all.js'></script>
<script src="https://cdn.jsdelivr.net/npm/promise-polyfill"></script>
-->
</html>

templates/livraria/home.html
{% extends 'livraria/base.html' %}
{% load static %}

{% block content %}

<div class="limiter ">
 <div class="container " >
  <div class="jumbotron jumbotron-fluid " id="jumbotron">
    <div class="container">
      <h1 class="display-4  textoTituloJumbotron" id="textoTituloJumbotron">Bem vindo a Livraria</h1>
      <p class="lead text-white ">    “Há livros escritos para evitar espaços vazios na estante.” - Carlos Drummond de Andrade</p>
    </div>
  </div>
  <div class="row">


    {% for livro in livros %}
    <!-- 
    <div class="col-md4">
      -->


    {% if livro.estoque > 0 %}
    <div id="EspacoCard"> </div>
      <div class="card mb-3   text-white bg-dark p-l-1" >
    
        <div class="card-body text-white textRegisterForm">
          <h5 class="card-title text-white">Nome do livro: {{livro.nome}}</h5>
          <p class="card-text text-white textRegisterForm fs-12">Autor: {{livro.autor.nome}}</p>
          <p class="card-text text-white textRegisterForm fs-12">Editora: {{livro.editora.nome}}</p>
          <p class="card-text text-white textRegisterForm fs-12">Descrição: {{livro.descricao}}</p>
        </div>
        <ul class="list-group">
          <div class="textRegisterForm fs-14">
          <li class="list-group-item  border border-dark" id="textoCard">Categoria: {{livro.categoria.nome}}</li>
          <li class="list-group-item  border border-dark" id="textoCard">Número de páginas: {{livro.num_paginas}}</li>
          <li class="list-group-item  border border-dark" id="textoCard">Ano de lançamento: {{livro.ano}}</li>
          <li class="list-group-item  border border-dark" id="textoCard">Preço: {{livro.preco}}</li>
          <li class="list-group-item  border border-dark" id="textoCard">Quantidade disponível: {{livro.estoque}}</li>
          </div>
        </ul>
        <div class="card-body">
          <div class="text-center">
            <a href="{% url 'livraria:emprestarlivro' livro.id %}" class="btn btn-primary text-white">Realizar empréstimo</a>
          </div>
        </div>
    </div>
   
    {% endif %}
    {% endfor %}
 
  </div>
</div>
{% endblock %}

templates/livraria/register_user.html
{% extends 'livraria/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}





<div class="limiter">

    <div class="container-login100">
        <div class="wrap-login100 p-l-110 p-r-110 p-t-62 p-b-33">
        
            {% include 'livraria/message/message.html' %}

            <div class="container-login100-form-btn m-t-17">

                <form class="login100-form validate-form flex-sb flex-w" method="POST" autocomplete="off">
                    <span class="login100-form-title p-b-53">
						Registro de novo usuário
					</span>
                    {% csrf_token %}
                 
            
                        <div class="textRegisterForm">
                        {{form|crispy}}
                       
                        </div>
                    </div>
                    <button class="login100-form-btn " type="submit">
                        Salvar
                    </button>
                    <div class="p-t-10"></div>
                </form>

              
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/livraria/teste404.html
{% extends 'livraria/base.html' %}

{% block content %}
<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

<title>404 HTML Template by Colorlib</title>

<div class="limiter">
  <div class="container-login100">
      <div class="wrap-login100 p-l-110 p-r-110 p-t-62 p-b-33">
          <div class="container-login100-form-btn m-t-17">
            <div class="text-center">
              <i class="fa fa-exclamation-triangle fa-5x"" aria-hidden="true"></i>

                  <span class="login100-form-title p-b-53">
                    <h1>Oops! Página não encontrada</h1>
                    <h3>Lamentamos, mas a página solicitada não foi encontrada</h3>
                    <a href="/" class="btn btn-primary ">Voltar para página inicial</a>
                  </span>
                
            </div>
          </div>
      </div>
  </div>
</div>        

{%endblock%}