blog/urls.py
from django.urls import path, include
from django.contrib import admin
from django.contrib.auth import views


urlpatterns = [
    path('', include('blog.urlsView')),
]

livraria/urls.py
from django.urls import path, include
from django.conf.urls import url

from django.contrib.auth import views
from django.contrib import admin


from django.views.generic.base import TemplateView
from .views import SignUpView, IndexView ,CreateLivroView, CreateEditoraView, CreateAutorView,CreateEmprestimoLivro, ListEmprestimosView, UpdateEmprestimoView, LivrosListView,LivrosDetailView, UpdateLivroView, DeleteLivroView, ProfileUserView, UpdateUserView

from django.contrib.auth import views as auth_views

app_name = 'livraria'

urlpatterns = [
    path('', IndexView.as_view(), name='home'),

    url(r'^atualizarconta/(?P<pk>[0-9]+)/$', UpdateUserView.as_view(), name='updateuser'),
    path('minhaconta', ProfileUserView.as_view(), name='profileuser'),
    #Cadastros
    path('registrousuario', SignUpView.as_view(), name='registeruser'),
    path('cadastrolivro', CreateLivroView.as_view(),name='cadastrarlivro'),
    path('cadastroeditora', CreateEditoraView.as_view(), name='cadastrareditora'),
    path('cadastroautor', CreateAutorView.as_view(), name='cadastrarautor'),

    #Emprestimo
    path('<int:pk>/emprestimolivro/', CreateEmprestimoLivro.as_view(), name='emprestarlivro'),

    path('exibiremprestimos', ListEmprestimosView.as_view(), name='listaremprestimos'),


     url(r'^devolucaolivro/(?P<pk>[0-9]+)/$', UpdateEmprestimoView.as_view(), name='devolverlivro'),

    #Exibição de livros
    path('exibirlivros', LivrosListView.as_view(), name='listarlivros'),

    #detalhe
    url(r'^detalhelivro/(?P<pk>[0-9]+)/$', LivrosDetailView.as_view(), name='detaillivro'),

    #Editar

    url(r'^edicaolivro/(?P<pk>[0-9]+)/$', UpdateLivroView.as_view(), name='editarlivro'),

    #excluir livro
    path('<int:pk>deletarlivro', DeleteLivroView.as_view(), name='deletelivro'),

    #Devolver Livro
    ##path('/livraria_devolver_livro/<int:pk>',livraria_devolver_livro, name='livrariadevolverlivro')

]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views
from django.contrib.auth import views as auth_views

urlpatterns = [
  
    path('admin/', admin.site.urls),
    path('accounts/',include('django.contrib.auth.urls')),
   # path('accounts/login/', views.LoginView.as_view(), name='login'),
   # path('accounts/logout/', views.LogoutView.as_view(next_page='/'), name='logout'),
    #path('accounts/password_change/', views.PasswordChangeForm.as_view(), name='change'),
 
    path('blog', include('blog.urls'), name='blog'),  
    path('', include('livraria.urls')),
 
]

blog/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.db.models import Sum


class Post(models.Model): # Utilizando Herança com Python Post é um Model
    # Definindo a chave estrangeira 
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()


    create_date = models.DateField(auto_now=True)

    #definindo data e hora e o campo pode ser nulo
    published_date = models.DateField(blank=True, null=True)
    views = models.BigIntegerField(default=0)
    

    def publish(self):
        #Pega a data e hora atual e altera a data de publicação para realizar o salvamento de dados no banco de dados
        self.published_date = timezone.now()
        self.save()

    def __str__(self): #Retorna a string do objeto em memória
        return '{} ({})'.format(self.title, self.author)

    def approved_comments(self):
        return self.comments.filter(approved_comment=True)


    def likes_count(self):

        count = self.opinion.aggregate(Sum('like'))

        if count['like__sum'] == None :
            count['like__sum'] = 0
    
        return count['like__sum'] #retorna a quantidade de PostLike no Post, como sendo filtro a proprio objeto Post

    def deslikes_count(self):
        count = self.opinion.aggregate(Sum('deslike'))

        if count['deslike__sum'] == None :
            count['deslike__sum'] = 0

        return count['deslike__sum']

class Opinion(models.Model):
    like = models.IntegerField(default=0)
    deslike = models.IntegerField(default=0)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    post = models.ForeignKey('blog.Post', on_delete=models.CASCADE, related_name='opinion')
    create_date = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return "'{}' '{}' '{}' '{}'".format(self.post.title, self.user,self.like,self.deslike)

class PostLike(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    post = models.ForeignKey('blog.Post', on_delete=models.CASCADE)
    create_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "'{}' - '{}'".format(self.post.title, self.user)

class Comment(models.Model):
    post = models.ForeignKey('blog.Post', on_delete=models.CASCADE, related_name='comments')
    author = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save()

    def __str__(self):
        return self.text

blog/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'text',)


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('author', 'text',)

blog/views.py
import datetime
from django.utils import timezone
from .models import Post, Comment, PostLike, Opinion, User
from django.shortcuts import render, get_object_or_404, redirect
from .forms import PostForm, CommentForm
from django.contrib.auth.decorators import login_required

# Create your views here.
#Recebe requisição


@login_required
def post_list(request):
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date') 
    return render(request, 'blog/post_list.html', {'posts':posts})
    
@login_required
def post_detail (request, pk):
    post = get_object_or_404(Post, pk=pk)

    post.views += 1
    post.save()


    cont_likes_total = post.likes_count()

    cont_deslikes_total = post.deslikes_count()

    percentApproval = 0
    percentDisapproval = 0

    if not cont_likes_total == 0 and cont_deslikes_total == 0 : 

        percentApproval = cont_likes_total / ( cont_likes_total + cont_deslikes_total) * 100

        percentDisapproval = cont_deslikes_total / ( cont_deslikes_total +  cont_likes_total) * 100


    if percentApproval < 0:
        percentApproval = 0
    
    elif percentDisapproval < 0:
        percentDisapproval = 0

    print('Aprroval:', percentApproval)
    print('Disapprova: ',percentDisapproval)

    return render(request, 'blog/post_detail.html',{'post': post, 'approval': percentApproval, 'disapproval': percentDisapproval})




@login_required
def post_new(request):

    if request.method == "POST":
         form = PostForm(request.POST)
         if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('blog:post_detail', pk=post.pk)
    else:
        form = PostForm()
    return render(request, 'blog/post_edit.html', {'form': form})

@login_required
def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('blog:post_detail', pk=post.pk)
    else:
        form = PostForm(instance=post)
    return render(request, 'blog/post_edit.html', {'form': form})

@login_required
def post_draft_list(request):
    post = Post.objects.filter(published_date__isnull=True).order_by('created_date')
    return render(request, 'blog/post_draft_list.html', {'post': post})

@login_required
def post_publish(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.publish()
    return redirect('blog:post_detail', pk=pk)

@login_required
def publish(self):
    self.published_date = timezone.now()
    self.save()

@login_required
def post_remove(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.delete()
    return redirect('blog:post_list')

@login_required
def post_like(request, pk):

    try:
        op = Opinion.objects.filter(post_id = pk, user= request.user).values()


        if len(op) == 0 :
            opinion = Opinion.objects.create(post_id=pk, user= request.user, like = 1, deslike = 0)
            opinion.save()

        else:
            print(op[0]['id'])
            auxOp = Opinion.objects.get(id = op[0]['id'])
          
            if auxOp.deslike >= 1:
                auxOp.deslike -=1
                auxOp.like += 1
            
            auxOp.save()

    except Opinion.DoesNotExist :
        opinion = Opinion.objects.create(post_id=pk, user= request.user, like = 1, deslike = 0)
        opinion.save()

    return redirect('blog:post_detail', pk = pk) 


@login_required
def post_deslike(request, pk):

    try:
        op = Opinion.objects.filter(post_id = pk, user= request.user).values()


        if len(op) == 0 :
            opinion = Opinion.objects.create(post_id=pk, user= request.user, like = 0, deslike = 1)
            opinion.save()

        else:
            auxOp = Opinion.objects.get(id = op[0]['id'])
            if auxOp.like >= 1:
                auxOp.deslike +=1
                auxOp.like -= 1
            
            auxOp.save()

    except Opinion.DoesNotExist :
        opinion = Opinion.objects.create(post_id=pk, user= request.user, like = 0, deslike = 1)
        opinion.save()

    return redirect('blog:post_detail', pk = pk) 

@login_required
def add_comment_to_post(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            return redirect('blog:post_detail', pk=post.pk)
    else:
        form = CommentForm()
    return render(request, 'blog/add_comment_to_post.html', {'form': form})


@login_required
def comment_approve(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.approve()
    return redirect('blog:post_detail', pk=comment.post.pk)

@login_required
def comment_remove(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.delete()
    return redirect('blog:post_detail', pk=comment.post.pk)

templates/blog/add_comment_to_post.html
{% extends 'blog/base.html' %}

{% block content %}
    <h1>New comment</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Send</button>
    </form>
{% endblock %}

templates/blog/base.html
<!DOCTYPE html>
{% load static %}


<html>
    <head>
        <title>Django Girls blog</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="{% static 'css/blog.css' %}">
       
    </head>

    <body>
        <div class="page-header">
            {% if user.is_authenticated %}
                <a href="{% url 'blog:post_new' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
                <a href="{% url 'blog:post_draft_list' %}" class="top-menu"><span class="glyphicon glyphicon-edit"></span></a>
                <p class="top-menu">Hello {{ user.username }} <small>(<a href="{% url 'logout' %}">Log out</a>)</small></p>
                <a href="{% url 'livraria:home' %}" class="top-menu"><span class="glyphicon glyphicon-book	
                    "></span>Conheça a nossa livraria</a>


            {% else %}
                <a href="{% url 'login' %}" class="top-menu"><span class="glyphicon glyphicon-lock"></span></a>
            {% endif %}
            <h1><a href="{% url 'blog:post_list' %}">Django Girls Blog</a></h1>
        </div>

        <div class="content container">
            <div class="row">
                <div class="col-md-8">
                {% block content %}
                {% endblock %}
                </div>
            </div>
        </div>
</html>

templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block content %}
    <div class="post">
        {% if post.published_date %}
            <div class="date">
                {{ post.published_date }}
            </div>

            {% else %}
                <a class="btn btn-default" href="{% url 'blog:post_publish' pk=post.pk %}">Publish</a>
                <a class="btn btn-default" href="{% url 'blog:post_remove' pk=post.pk %}"><span class="glyphicon glyphicon-remove"></span></a>

            {% endif %}
          

        {% if user.is_authenticated %}
        <a class="btn btn-default" href="{% url 'blog:post_edit' pk=post.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
        {% endif %}
        <h2>{{ post.title }}</h2>
        <p>{{ post.text|linebreaksbr }}</p>
        <div class="date heart">{{post.views}} views &nbsp; | &nbsp;

            <a href="{% url 'blog:post_like' pk=post.pk %}"> 
                
                {% if liked %}
            <!----    <span class="glyphicon glyphicon-heart liked"></span></a> -->
            <span class="glyphicon glyphicon-thumbs-up liked"></span></a>
            
                {% else %}
                <span class="glyphicon glyphicon-thumbs-up"></span></a>
                {% endif %}
            
               
                {{post.likes_count}} 
           

                | &nbsp;
            <a href="{% url 'blog:post_deslike' pk=post.pk %}">
              <span class="glyphicon glyphicon-thumbs-down"></span>

            </a>

            {{post.deslikes_count}}
           
            | &nbsp; 

            
        </div>

        <div class="heart"> 
            Aprovação:  {{approval | floatformat:2}} %
            Reprovação: {{disapproval | floatformat:2}} %
           
        </div>
        
    </div>

    <hr>
    <a class="btn btn-default" href="{% url 'blog:add_comment_to_post' pk=post.pk %}">Add comment</a>
    
    {% for comment in post.comments.all %}
    {% if user.is_authenticated or comment.approved_comment %}
    <div class="comment">
        <div class="date">
            {{ comment.created_date }}
            {% if not comment.approved_comment %}
                <a class="btn btn-default" href="{% url 'blog:comment_remove' pk=comment.pk %}"><span class="glyphicon glyphicon-remove"></span></a>
                <a class="btn btn-default" href="{% url 'blog:comment_approve' pk=comment.pk %}"><span class="glyphicon glyphicon-ok"></span></a>
            {% endif %}
        </div>
        <strong>{{ comment.author }}</strong>
        <p>{{ comment.text|linebreaks }}</p>
    </div>
    {% endif %}
{% empty %}
    <p>No comments here yet :(</p>
{% endfor %}
{% endblock %}

templates/blog/post_draft_list.html
{% extends 'blog/base.html' %}

{% block content %}
    {% for post in posts %}
        <div class="post">
            <p class="date">created: {{ post.created_date|date:'d-m-Y' }}</p>
            <h1><a href="{% url 'blog:post_detail' pk=post.pk %}">{{ post.title }}</a></h1>
            <p>{{ post.text|truncatechars:200 }}</p>
        </div>
    {% endfor %}
{% endblock %}

templates/blog/post_edit.html
{% extends 'blog/base.html' %}

{% block content %}
    <h2>New post</h2>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>

{% endblock %}

templates/blog/post_list.html
{% extends 'blog/base.html' %}

{% block content %}
{% for post in posts %}
<div class="post">
    <div class="date">
        {{ post.published_date }}
    </div>
    <h2><a href="{% url 'blog:post_detail' pk=post.pk %}">{{ post.title }}</a></h2>
    <p>{{ post.text|linebreaksbr }}</p> <!--- Utilizando filtro e realizando quebra de linha---> 
    <a href="{% url 'blog:post_detail' pk=post.pk %}">Comments: {{ post.approved_comments.count }}</a>

</div>
{%empty%}
<h2>  Sorry, no posts =C</h2>

{% endfor %}
{% endblock %}