blog/urls.py
from django.urls import path, include
from django.contrib import admin
from django.contrib.auth import views


urlpatterns = [
    path('', include('blog.urlsView')),
]

livraria/urls.py
from django.urls import path, include
from django.conf.urls import url

from django.contrib.auth import views
from django.contrib import admin


from django.views.generic.base import TemplateView
from .views import SignUpView, IndexView ,CreateLivroView, CreateEditoraView, CreateAutorView,CreateEmprestimoLivro, ListEmprestimosView, UpdateEmprestimoView, LivrosListView,LivrosDetailView, UpdateLivroView, DeleteLivroView, ProfileUserView, UpdateUserView

from django.contrib.auth import views as auth_views

app_name = 'livraria'

urlpatterns = [
    path('', IndexView.as_view(), name='home'),

    url(r'^atualizarconta/(?P<pk>[0-9]+)/$', UpdateUserView.as_view(), name='updateuser'),
    path('minhaconta', ProfileUserView.as_view(), name='profileuser'),
    #Cadastros
    path('registrousuario', SignUpView.as_view(), name='registeruser'),
    path('cadastrolivro', CreateLivroView.as_view(),name='cadastrarlivro'),
    path('cadastroeditora', CreateEditoraView.as_view(), name='cadastrareditora'),
    path('cadastroautor', CreateAutorView.as_view(), name='cadastrarautor'),

    #Emprestimo
    path('<int:pk>/emprestimolivro/', CreateEmprestimoLivro.as_view(), name='emprestarlivro'),

    path('exibiremprestimos', ListEmprestimosView.as_view(), name='listaremprestimos'),


     url(r'^devolucaolivro/(?P<pk>[0-9]+)/$', UpdateEmprestimoView.as_view(), name='devolverlivro'),

    #Exibição de livros
    path('exibirlivros', LivrosListView.as_view(), name='listarlivros'),

    #detalhe
    url(r'^detalhelivro/(?P<pk>[0-9]+)/$', LivrosDetailView.as_view(), name='detaillivro'),

    #Editar

    url(r'^edicaolivro/(?P<pk>[0-9]+)/$', UpdateLivroView.as_view(), name='editarlivro'),

    #excluir livro
    path('<int:pk>deletarlivro', DeleteLivroView.as_view(), name='deletelivro'),

    #Devolver Livro
    ##path('/livraria_devolver_livro/<int:pk>',livraria_devolver_livro, name='livrariadevolverlivro')

]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views
from django.contrib.auth import views as auth_views

urlpatterns = [
  
    path('admin/', admin.site.urls),
    path('accounts/',include('django.contrib.auth.urls')),
   # path('accounts/login/', views.LoginView.as_view(), name='login'),
   # path('accounts/logout/', views.LogoutView.as_view(next_page='/'), name='logout'),
    #path('accounts/password_change/', views.PasswordChangeForm.as_view(), name='change'),
 
    path('blog', include('blog.urls'), name='blog'),  
    path('', include('livraria.urls')),
 
]

templates/profile.html
{% extends 'livraria/base.html' %}

{% block content %}

<div class="limiter">
    <div class="container-login100">
     
        <div class="wrap-login100 p-l-110 p-r-110 p-t-62 p-b-33">
            <span class="login100-form-title p-b-53">
           
                Meu Perfil
                {% include 'livraria/message/message.html' %}
              </span>
              <div class="textRegisterForm">
                <div class="card mb-3 border border-dark">
                    <div class="card-header bg-dark mb-3 text-white">
                      <div class="text-center ">
                        <i class="fa fa-user fa-4x" aria-hidden="true"></i>
                            
                        </div>
                    </div>
                    <div class="text-center">
                    <div class="card-body">
                     Usuário: {{user.username}}
                    </div>
                        <ul class="list-group">
                            <div class="textRegisterForm fs-14">
                                <li class="list-group-item  border border-dark"  id="textoCard">E-mail: {{user.email}}</li>

                                <li class="list-group-item  border border-dark"  id="textoCard">Primeiro nome: 
                                 {% if user.first_name %}
                                   {{user.first_name}}
                                 {% else %}
                                  Não há primeiro nome cadastrado (Por favor atualize no botão abaixo!)
                                {% endif %}
                                </li>

                                <li class="list-group-item  border border-dark"  id="textoCard">Último nome: 
                                  {% if user.last_name %}
                                    {{user.last_name}}
                                  {% else %}
                                   Não há último nome cadastrado (Por favor atualize no botão abaixo!)

                                  {% endif %}
                                </li>


                                <li class="list-group-item  border border-dark"  id="textoCard">Telefone: 
                                   {% if user.fone %}
                                    {{user.fone}}
                                    
                                   {% else %}
                                     Não há telefone cadastrado (Por favor atualize no botão abaixo!)

                                   {% endif %}
                                </li>
                     
                            </div>
                            <a href="{% url 'livraria:updateuser' user.id %}" class="btn btn-warning">Atualizar perfil</a>
                            <a href="/" class="btn btn-primary">Voltar para tela inicial</a>
                        </ul>
                    </div>
                  </div>

            </div>

        </div>
    </div>
</div>


{% endblock %}

templates/update_profile.html
{% extends 'livraria/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}

<div class="limiter">
    <div class="container-login100">
        <div class="wrap-login100 p-l-110 p-r-110 p-t-62 p-b-33">
            {% include 'livraria/message/message.html' %}
                <form class="login100-form validate-form flex-sb flex-w" method="POST" autocomplete="off">
                    <span class="login100-form-title p-b-53">

                    
                    Atualizar perfil
                    </span>
                    {% csrf_token %}
                    <div class="textRegisterForm">
                        {{form|crispy}}
                    <a href="{% url 'password_change' %}" class="login100-form btn btn-warning">Atualizar senha</a>
                    <button class="login100-form btn btn-primary" type="submit">
                        Salvar
                    </button>
                    <a href="{% url 'livraria:profileuser' %}" class="login100-form btn btn-warning">Voltar para perfil</a>
                    <div class="p-t-10"></div>
                    </div>
            </form>  
        </div>
    </div>
</div>


{% endblock %}