blog/urls.py
from django.urls import path, include
from django.contrib import admin
from django.contrib.auth import views


urlpatterns = [
    path('', include('blog.urlsView')),
]

livraria/urls.py
from django.urls import path, include
from django.conf.urls import url

from django.contrib.auth import views
from django.contrib import admin


from django.views.generic.base import TemplateView
from .views import SignUpView, IndexView ,CreateLivroView, CreateEditoraView, CreateAutorView,CreateEmprestimoLivro, ListEmprestimosView, UpdateEmprestimoView, LivrosListView,LivrosDetailView, UpdateLivroView, DeleteLivroView, ProfileUserView, UpdateUserView

from django.contrib.auth import views as auth_views

app_name = 'livraria'

urlpatterns = [
    path('', IndexView.as_view(), name='home'),

    url(r'^atualizarconta/(?P<pk>[0-9]+)/$', UpdateUserView.as_view(), name='updateuser'),
    path('minhaconta', ProfileUserView.as_view(), name='profileuser'),
    #Cadastros
    path('registrousuario', SignUpView.as_view(), name='registeruser'),
    path('cadastrolivro', CreateLivroView.as_view(),name='cadastrarlivro'),
    path('cadastroeditora', CreateEditoraView.as_view(), name='cadastrareditora'),
    path('cadastroautor', CreateAutorView.as_view(), name='cadastrarautor'),

    #Emprestimo
    path('<int:pk>/emprestimolivro/', CreateEmprestimoLivro.as_view(), name='emprestarlivro'),

    path('exibiremprestimos', ListEmprestimosView.as_view(), name='listaremprestimos'),


     url(r'^devolucaolivro/(?P<pk>[0-9]+)/$', UpdateEmprestimoView.as_view(), name='devolverlivro'),

    #Exibição de livros
    path('exibirlivros', LivrosListView.as_view(), name='listarlivros'),

    #detalhe
    url(r'^detalhelivro/(?P<pk>[0-9]+)/$', LivrosDetailView.as_view(), name='detaillivro'),

    #Editar

    url(r'^edicaolivro/(?P<pk>[0-9]+)/$', UpdateLivroView.as_view(), name='editarlivro'),

    #excluir livro
    path('<int:pk>deletarlivro', DeleteLivroView.as_view(), name='deletelivro'),

    #Devolver Livro
    ##path('/livraria_devolver_livro/<int:pk>',livraria_devolver_livro, name='livrariadevolverlivro')

]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views
from django.contrib.auth import views as auth_views

urlpatterns = [
  
    path('admin/', admin.site.urls),
    path('accounts/',include('django.contrib.auth.urls')),
   # path('accounts/login/', views.LoginView.as_view(), name='login'),
   # path('accounts/logout/', views.LogoutView.as_view(next_page='/'), name='logout'),
    #path('accounts/password_change/', views.PasswordChangeForm.as_view(), name='change'),
 
    path('blog', include('blog.urls'), name='blog'),  
    path('', include('livraria.urls')),
 
]

livraria/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, ReadOnlyPasswordHashField
from django import forms
from django.utils import timezone
from datetime import datetime, date
from django.conf import settings


from .models import CustomUsuario, Livro, Editora, Categoria, Autor, EmprestimoLivro
from mysite.settings import DATE_INPUT_FORMATS, TIME_INPUT_FORMATS

class DateInput(forms.DateInput):
    input_type = 'date'
    


CATEGORIA_CHOICES = (
    ('Filosofia', 'Filosofia'),
    ('Religiao','Religiao'),
    ('Ciencia','Ciencia'),
    ('Romance','Romance'),
    ('Historia','Historia'),
    ('Terror', 'Terror'),
    ('Suspense', 'Suspense'),
    )


class CustomUsuarioCreationForm(UserCreationForm):
    class Meta:
        model = CustomUsuario
        fields = ('first_name', 'last_name', 'fone', 'email')


    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        user.username = self.cleaned_data['email']
        

        if commit:
            user.save()

        return user


class CustomUsuarioChangeForm(UserChangeForm):
    password = ReadOnlyPasswordHashField(label=("Senha"),
        help_text=("Para atualizar a senha, você precisa clicar no botão de atualizar senha abaixo"))
    class Meta:
        model = CustomUsuario
        fields = ('first_name', 'last_name', 'fone', 'email')


class LivroCreationForm(forms.ModelForm):

    categoria = forms.ChoiceField(choices=CATEGORIA_CHOICES, label='Categoria')
    ano = forms.DateField(widget=DateInput, label='Ano')
    descricao = forms.CharField(widget=forms.Textarea())

    class Meta:
        model = Livro
        fields = ('nome', 'preco', 'estoque', 'edicao', 'num_paginas', 'autor', 'editora')


class EditoraCreateForm(forms.ModelForm):
    rua = forms.CharField(max_length=100,label='Rua')
    bairro = forms.CharField(max_length=100,label='Bairro')
    numero = forms.IntegerField(initial = 0,label='Número')
    cidade = forms.CharField(max_length=100,label='Cidade')
    estado = forms.CharField(max_length=100,label='Estado')

    class Meta:
        model = Editora
        fields = ('nome',)


class AutorCreationForm(forms.ModelForm):
    data_nascimento = forms.DateField(widget=DateInput, label='Data de nascimento')

    class Meta:
        model = Autor
        fields = ('nome',)


class EmprestimoLivroCreationForm(forms.ModelForm):
    data_inicial = forms.DateField(label='Data de início',disabled=True,initial=date.today)
    data_devolucao = forms.DateField(widget=DateInput, label='Digite a data de devolução')
    preco = forms.DecimalField(label='Preco a pagar pelo emprestimo',decimal_places=2,disabled=True, initial=0)
    
    
    class Meta:
        model = EmprestimoLivro
        fields = ('quantidade', )

livraria/views.py
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin


from django.views.generic.edit import CreateView
from django.views.generic import TemplateView, ListView, DetailView, DeleteView, UpdateView

from django.urls import reverse_lazy

from .forms import CustomUsuarioCreationForm, CustomUsuarioChangeForm ,LivroCreationForm, EditoraCreateForm, AutorCreationForm, EmprestimoLivroCreationForm

from .models import Livro, Categoria, Autor, Editora, Endereco, EmprestimoLivro, CustomUsuario

from django.shortcuts import render, reverse, redirect, get_object_or_404
from django.contrib import messages
from django.utils import timezone

from django.contrib.auth.forms import PasswordChangeForm



# ----------- Variáveis globais ------------

verificacao_campo_data_devolucao = None
verificacao_campo_quantidade = None
aux_instance_form = None
verificacao_botao_salvar = True




# ----------- DeleteView ------------

class DeleteLivroView(DeleteView):
    model = Livro
    template_name = 'livraria/forms/livro_confirm_delet.html'
    success_url = reverse_lazy('livraria:listarlivros')
    success_message = 'Livro deletado com sucesso!'


# ----------- DetailView ------------

class LivrosDetailView(DetailView):
     model = Livro
    #queryset = Livro.objects.all()
     template_name = 'livraria/produto/detalhe_livro.html'

    #def get(self, request, *args, **kwargs):
     #   livro = get_object_or_404(Livro, pk=kwargs['pk'])
      #  context = {'livro': livro}
      #  return render(request, 'livraria/produto/detalhe_livro.html', context)
   # def get_object(self):
     #  id_ = self.kwargs.get("id")
      #  return get_object_or_404(Livro, id=id_)

# ----------- ListView ------------

class LivrosListView(ListView):
    model = Livro
    template_name = 'livraria/produto/exibir_livros.html'
    queryset = Livro.objects.all()
    context_object_name = 'livros'


class ListEmprestimosView(ListView):
    model = EmprestimoLivro
    template_name = 'livraria/produto/exibir_emprestimos.html'
    queryset = EmprestimoLivro.objects.all()
    context_object_name = 'emprestimos'


class IndexView(ListView):
    models = Livro
    template_name = 'livraria/home.html'
    queryset = Livro.objects.all()
    context_object_name = 'livros'


# ----------- CreateView ------------

class SignUpView(SuccessMessageMixin,CreateView):
    form_class = CustomUsuarioCreationForm
    success_url = reverse_lazy('livraria:registeruser')
    template_name = 'livraria/register_user.html'
    success_message = 'Cadastro efetuado com sucesso!'


class CreateLivroView(LoginRequiredMixin, SuccessMessageMixin,CreateView):
    login_url = 'login'
    redirect_field_name = 'login'
    form_class = LivroCreationForm
    success_url = reverse_lazy('livraria:cadastrarlivro')
    template_name = 'livraria/forms/add_livro.html'

    def get(self, request, *args, **kwargs):
        autores = Autor.objects.all()
        editoras = Editora.objects.all()
        formLivro = super(CreateLivroView, self).get_form()
        context = {'formLivro': formLivro,
                   'autores': autores,
                   'editoras': editoras}
        return render(request, 'livraria/forms/add_livro.html',context)

    def post(self, request, *args, **kwargs):
        formLivro = self.get_form()
        autores = Autor.objects.all()
        editoras = Editora.objects.all()


        if formLivro.is_valid():
            nome = formLivro.cleaned_data['nome']
            preco = formLivro.cleaned_data['preco']
            estoque = formLivro.cleaned_data['estoque'] 
            edicao = formLivro.cleaned_data['edicao']
            ano = formLivro.cleaned_data['ano']
            num_paginas = formLivro.cleaned_data['num_paginas']
            descricao = formLivro.cleaned_data['descricao']

            editora = formLivro.cleaned_data['editora']
            autor = formLivro.cleaned_data['autor'] 
            categoria = formLivro.cleaned_data['categoria']


            print(formLivro.cleaned_data)
            if estoque <= 0:
                messages.error(request,'O estoque não pode ser zero ou negativo')

            elif num_paginas <= 0:
                messages.error(request,'O número de páginas não pode ser zero ou negativo')

            else:

                aux_editora, created = Editora.objects.get_or_create(id=editora.id)
                aux_autor, created = Autor.objects.get_or_create(id=autor.id)
                aux_categoria, created = Categoria.objects.get_or_create(nome=categoria)
            
                preco_total = preco * estoque
                
                livro, created = Livro.objects.get_or_create(nome=nome, preco=preco, estoque=estoque, edicao=edicao, ano=ano, num_paginas=num_paginas, descricao=descricao, editora=aux_editora, autor=aux_autor, categoria=aux_categoria, preco_total=preco_total)

                messages.success(request,'Cadastro realizado com sucesso!')
                livro.save()
                
                formLivro = LivroCreationForm()


        context = {'formLivro': formLivro,
                   'editoras': editoras,
                   'autores': autores
                  }

        return render(request, 'livraria/forms/add_livro.html' , context)


class CreateEditoraView(LoginRequiredMixin, CreateView):
    login_url = 'login'
    redirect_field_name = 'login'
    model = Editora
    form_class = EditoraCreateForm
    success_url = reverse_lazy('livraria:cadastrareditora')

    def get(self, request, *args, **kwargs):
        form = super(CreateEditoraView, self).get_form()
        context = {'formEditora': form}
        return render(request, 'livraria/forms/add_editora.html', context)

    def post(self, request, *args, **kwargs):
        formEditora = self.get_form()

        if formEditora.is_valid():

            rua = formEditora.cleaned_data['rua']
            bairro = formEditora.cleaned_data['bairro']
            cidade = formEditora.cleaned_data['cidade']
            estado = formEditora.cleaned_data['estado']
            numero = formEditora.cleaned_data['numero']
            nomeEditora = formEditora.cleaned_data['nome']

            endereco, created = Endereco.objects.get_or_create(rua=rua, bairro=bairro, numero=numero, cidade=cidade, estado=estado)
            editora, created = Editora.objects.get_or_create(nome=nomeEditora, endereco=endereco)
            messages.success(request,'Cadastro realizado com sucesso!')
            editora.save()

        formEditora = EditoraCreateForm()

        return render(request, 'livraria/forms/add_editora.html', {'formEditora': formEditora})


class CreateAutorView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    login_url = 'login'
    redirect_field_name = 'login'
    form_class = AutorCreationForm
    template_name = 'livraria/forms/add_autor.html'
    success_url = reverse_lazy('livraria:cadastrarautor')

    def get(self, request, *args, **kwargs):
        formAutor = super(CreateAutorView, self).get_form()
        context = {'formAutor': formAutor}
        return render(request, 'livraria/forms/add_autor.html',context)

    def post(self, request, *args, **kwargs):
        formAutor = self.get_form()

        if formAutor.is_valid():

            nome = formAutor.cleaned_data['nome']
            data_nascimento = formAutor.cleaned_data['data_nascimento']
            print('data nascimento:', data_nascimento)
            autor, created = Autor.objects.get_or_create(nome=nome, data_nascimento=data_nascimento)
            messages.success(request,'Cadastro realizado com sucesso!')
            autor.save()

        formAutor = AutorCreationForm()
        

        return render(request, 'livraria/forms/add_autor.html' , {'formAutor': formAutor})


class CreateEmprestimoLivro(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    login_url = 'login'
    redirect_field_name = 'login'
    form_class = EmprestimoLivroCreationForm
    template_name = 'livraria/forms/emprestimo_livro.html'

    def get(self, request, *args, **kwargs):
        livro = Livro.objects.get(pk=self.kwargs['pk'])
        formEmprestimo = super(CreateEmprestimoLivro, self).get_form()
        global verificacao_botao_salvar
        #aux_instance_form = formEmprestimo


        context = {'formEmprestimo': formEmprestimo,
                   'livro': livro, 
                   'verificacao_botao_salvar':verificacao_botao_salvar
                   }
        
        return render(request, 'livraria/forms/emprestimo_livro.html',context)

    def post(self, request, *args, **kwargs):

        livro = Livro.objects.get(pk=self.kwargs['pk'])
        global verificacao_campo_data_devolucao
        global verificacao_campo_quantidade
        global aux_instance_form
        global verificacao_botao_salvar

        if verificacao_campo_data_devolucao == None and verificacao_campo_quantidade == None: 
            formEmprestimo = self.get_form()
            aux_instance_form = formEmprestimo
           # print('FORM emprestimo:', formEmprestimo)
            print('CAiu na verificação da data')
        else:
            print('CAiu no else')
            formEmprestimo = aux_instance_form
      
        if formEmprestimo.is_valid():
            quantidade = formEmprestimo.cleaned_data['quantidade']
            data_inicial = formEmprestimo.cleaned_data['data_inicial']
            data_devolucao = formEmprestimo.cleaned_data['data_devolucao']
            preco_total = formEmprestimo.cleaned_data['preco']
            diferenca_data = data_devolucao - data_inicial

            print('DATA INCIAL', data_inicial)
            print('DATA DEVOULAÇÂO:', data_devolucao)
            print('DIFERENÇA', diferenca_data.days)
            if quantidade == 0:
                
                messages.error(request,'A quantidade não pode ser zero')

            elif quantidade > livro.estoque:

templates/livraria/produto/detalhe_livro.html
{% extends 'livraria/base.html' %}
{% load static %}

{% block content %}




<div class="limiter">
  <div class="container-login100">
      <div class="wrap-login100 p-l-110 p-r-110 p-t-62 p-b-33">
          <div class="container-login100-form-btn m-t-17">
 
                  <span class="login100-form-title p-b-53">
                    Detalhes Livro

                  </span>
             
                  <div class="container-detalhe ">
                    <div class="textRegisterForm">
                    <div class="card text-white bg-dark">
                      <div class="card-body">
                        <div class="text-center">
                        <h5 class="card-title">Nome do livro: {{object.nome}}</h5>
                        <p class="card-text textRegisterForm text-white">Descrição do livro: {{object.descricao}}</p>
                      </div>
                      </div>
              
                      <ul class="list-group">
                        <div class="text-center">
                          <li class="list-group-item border border-dark" id="textoCard">Editora: {{object.editora.nome}}</li>
                        <li class="list-group-item border border-dark" id="textoCard">Autor: {{object.autor.nome}}</li>
                        <li class="list-group-item border border-dark" id="textoCard">Categoria: {{object.categoria.nome}}</li>
                        <li class="list-group-item border border-dark" id="textoCard">Número de páginas: {{object.num_paginas}}</li>
                        <li class="list-group-item border border-dark" id="textoCard">Ano de lançamento: {{object.ano}}</li>
                        <li class="list-group-item border border-dark" id="textoCard">Preço: {{object.preco}}</li>
                        <li class="list-group-item border border-dark" id="textoCard">Quantidade em estoque: {{object.estoque}}</li>
                        </div>
                      </ul>
              
                      <div class="card-body">
                       <div class="text-center">
                          <div class="btn-group" role="group">
                        <a href="{% url 'livraria:listarlivros' %}" class="btn btn-primary ">Voltar</a>
                        <a href="{% url 'livraria:editarlivro' livro.id %}" class="btn btn-warning">Editar</a>
                        <a href="{% url 'livraria:deletelivro' livro.id %}" class="btn btn-danger">Excluir</a>
                       </div>
                        </div>
                      </div>
              
                    </div>
                  </div>

                 

                <div>
              </div>
                  <div class="p-t-10"></div>
            </div>
          </div>
      </div>
  </div>
</div>

{% endblock %}

templates/livraria/produto/devolucao_emprestimo.html
{% extends 'livraria/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}



<div class="limiter">
    <div class="container-login100">
        <div class="wrap-login100 p-l-110 p-r-110 p-t-62 p-b-33">
            <div class="container-login100-form-btn m-t-17">
                <span class="login100-form-title p-b-53">
                    Devolução do livro
                </span>


            </div>
        </div>
    </div>
</div>
{% endblock %}            

templates/livraria/produto/exibir_emprestimos.html
{% extends 'livraria/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}


<div class="limiter">
    <div class="container-login100">
        
        
    {% if emprestimos %}
        <div class="tabelalivros p-l-15 p-r-31 p-t-62 p-b-33">
            {% include 'livraria/message/message.html' %}

            <span class="login100-form-title p-b-53">
                Meus empréstimos
            </span>
            
            <table class="table table-dark">
                <thead>
                    <tr>
                      
                            <th scope="col text-center">Livro</th>
                            <th scope="col">Data Inicial</th>
                            <th scope="col">Data de devolução</th>
                            <th scope="col" id="PrecoTotal">Preço do empréstimo</th>
                            <th scope="col">Quantidade</th>
                            <th scope="col">Status</th>
                            <th scope="col">Ação</th>
                       
                    </tr>
                </thead>
                    
                <tbody>
                    {% for emprestimo in emprestimos %}
                
                        {% ifchanged %}

                    <tr>
                        <td scope="row">{{emprestimo.livro.nome}}</td>
                        <td scope="row">{{emprestimo.data_inicial|date:'d-m-Y'}}</td>
                        <td scope="row">{{emprestimo.data_devolucao|date:'d-m-Y'}}</td>
                        <td scope="row">{{emprestimo.preco}}</td>
                        <td scope="row">{{emprestimo.quantidade}}</td>
                        <td id="id"> 
                            <input type="hidden" id="id">{{emprestimo.id}}</input>
                        </td>   

                        {% if emprestimo.ativo %}
                            <td scope="row">Ativo</td>
                        {% elif not emprestimo.ativo %}
                            <td scope="row">Devolvido</td>
                        {% endif %}
                        {% endifchanged %}
                        
                        {% if emprestimo.ativo %}
                        <td scope="row">
                            <a href="{% url 'livraria:devolverlivro' emprestimo.id %}" class="btn btn-primary active" role="button" aria-pressed="true">Devolver</a>
                        </td>
                        {% elif not emprestimo.ativo %}
                        
                        <td scope="row">
                            <button type="button"  class="btn btn-primary btn-sm">
                                <span class="material-icons">close</span>
                                Ação não disponivel
                             </button>
                        </td>

                       

                        {% endif %}

                    {% endfor %}
                            </tr> 
                    </tbody>

            </table>
        </div>
        {% else %}
        <div class="wrap-login100 p-l-110 p-r-110 p-t-62 p-b-33">
            <div class="container-login100-form-btn m-t-17">
            <span class="login100-form-title p-b-53">
                Aviso <i class="fa fa-exclamation-circle" aria-hidden="true"></i>
                <p class="fs-20"> Não há emprestimos!</p>

                <a href="/">
                    <button class="login100-form-btn  " type="submit">
                        Voltar
                    </button>
                    <div class="p-t-13"></div>
                </a>
                </span>
            </div>
        </div>
        {% endif %}
        </div>
</div>

{% endblock %}

templates/livraria/produto/exibir_livros.html
{% extends 'livraria/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}


<div class="limiter">
    <div class="container-login100">
        

    {% if livros %}
        <div class="tabelalivros p-l-15 p-r-31 p-t-62 p-b-33">
             
            <span class="login100-form-title p-b-53">
                Meus livros
            </span>
            
            <table class="table table-dark">
                <thead>
                    <tr>
                      
                            <th scope="col text-center">Produto</th>
                            <th scope="col">Preço unitário</th>
                            <th scope="col">Quantidade em estoque</th>
                            <th scope="col" id="PrecoTotal">Preço total</th>
                            <th scope="col">Ação</th>
                       
                    </tr>
                </thead>
                    
                <tbody>
                    {% for livro in livros %}
                
                    {% ifchanged %}

                    <tr>
                        <td scope="row">{{ livro.nome }}</td>
                        <td scope="row">{{ livro.preco }}</td>
                        <td scope="row">{{ livro.estoque }}</td>
                        <td scope="row">{{ livro.preco_total }}</td>
                        <td id="id"> 
                            <input type="hidden" >{{livro.id}}</input>
                        </td>   
                            <td scope="row">
                                
                                <a href="{% url 'livraria:detaillivro' livro.id %}" class="btn btn-primary active" role="button" aria-pressed="true">Exibir detalhes
                            </td>
                                {% endifchanged %}
                            {% endfor %}
                            </tr> 
                    </tbody>

            </table>
        </div>
        {% else %}
        <div class="wrap-login100 p-l-110 p-r-110 p-t-62 p-b-33">
            <div class="container-login100-form-btn m-t-17">
            <span class="login100-form-title p-b-53">
                Aviso <i class="fa fa-exclamation-circle" aria-hidden="true"></i>
                <p class="fs-20"> Não há livros cadastrados!</p>

                <a href="/">
                    <button class="login100-form-btn  " type="submit">
                        Voltar
                    </button>
                    <div class="p-t-13"></div>
                </a>
                </span>
            </div>
        </div>
        {% endif %}
        </div>
</div>

{% endblock %}